apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vaishnavi126/rds-backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "cloudbook.cbig0owqa8c2.ap-south-1.rds.amazonaws.com"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "Admin123"
            - name: DB_NAME
              value: "cloudbook"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
